package model;
// Generated 29 avr. 2016 00:01:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer idarticle;
     private AgentMedical agentMedical;
     private Forum forum;
     private String articlecontent;
     private String nomarticle;
     private Date date1;
     private Set commentaires = new HashSet(0);

    public Article() {
    }

    public Article(AgentMedical agentMedical, Forum forum, String articlecontent, String nomarticle, Date date1, Set commentaires) {
       this.agentMedical = agentMedical;
       this.forum = forum;
       this.articlecontent = articlecontent;
       this.nomarticle = nomarticle;
       this.date1 = date1;
       this.commentaires = commentaires;
    }
   
    public Integer getIdarticle() {
        return this.idarticle;
    }
    
    public void setIdarticle(Integer idarticle) {
        this.idarticle = idarticle;
    }
    public AgentMedical getAgentMedical() {
        return this.agentMedical;
    }
    
    public void setAgentMedical(AgentMedical agentMedical) {
        this.agentMedical = agentMedical;
    }
    public Forum getForum() {
        return this.forum;
    }
    
    public void setForum(Forum forum) {
        this.forum = forum;
    }
    public String getArticlecontent() {
        return this.articlecontent;
    }
    
    public void setArticlecontent(String articlecontent) {
        this.articlecontent = articlecontent;
    }
    public String getNomarticle() {
        return this.nomarticle;
    }
    
    public void setNomarticle(String nomarticle) {
        this.nomarticle = nomarticle;
    }
    public Date getDate1() {
        return this.date1;
    }
    
    public void setDate1(Date date1) {
        this.date1 = date1;
    }
    public Set getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set commentaires) {
        this.commentaires = commentaires;
    }




}


