package model;
// Generated 29 avr. 2016 00:01:12 by Hibernate Tools 4.3.1



/**
 * Visiteur generated by hbm2java
 */
public class Visiteur  implements java.io.Serializable {


     private Integer numvisiteur;

    public Visiteur() {
    }

   
    public Integer getNumvisiteur() {
        return this.numvisiteur;
    }
    
    public void setNumvisiteur(Integer numvisiteur) {
        this.numvisiteur = numvisiteur;
    }




}


